name: kevmoo_scripts
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.6.0
  build_cli_annotations: ^2.1.1
  collection: ^1.19.0
  git: ^2.3.2
  io: ^1.0.4
  package_config: ^2.1.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  stack_trace: ^1.12.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.0

dev_dependencies:
  build_cli: ^2.2.8
  build_runner: ^2.8.0
  dart_flutter_team_lints: ^3.0.0
  test: ^1.29.0
  test_descriptor: ^2.0.2

executables:
  git-goma: git_clean
  lint_cleanup:
  puppy:
  tighten:
  who_listen:
  skill-link: skill_link
