name: kevmoo_scripts
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  git: ^2.3.2
  io: ^1.0.4
  package_config: ^2.1.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  stack_trace: ^1.12.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.29.0
  test_descriptor: ^2.0.2

executables:
  git-goma: git_clean
  who_listen:
  tighten:
  lint_cleanup:
